# Defining Seach Terms
```{r}
year <- 1982:2022
microbiome_search <- glue("microbiome OR metagenomics OR metagenome AND {year}[PDAT]")
genomics_search <- glue("genomics AND {year}[PDAT]")
proteomics_search <- glue("proteomics AND {year}[PDAT]")
metabolomics_search <- glue("metabolomics AND {year}[PDAT]")
lipidomics_search <- glue("lipidomics AND {year}[PDAT]")
phenomics_search <- glue("phenomics AND {year}[PDAT]")
transcriptomics_search <- glue("transcriptomics AND {year}[PDAT]")
ml_search <- glue("(machine learning) AND {year}[PDAT]")
bioinfo_search <- glue("(bioinformatic*) AND {year}[PDAT]")
pharma_search <- glue("(pharmacogenomics*) AND {year}[PDAT]")
all_search <- glue("{year}[PDAT]")
```

# Getting Article Counts
```{r}
library(tictoc)
tic()

search_counts <- tibble(year = year,
       microbiome_search = microbiome_search,
       genomics_search = genomics_search,
       proteomics_search = proteomics_search,
       metabolomics_search = metabolomics_search,
       lipidomics_search = lipidomics_search,
       phenomics_search = phenomics_search,
       transcriptomics_search = transcriptomics_search,
       ml_search = ml_search,
       bioinfo_search = bioinfo_search,
       pharma_search = pharma_search,
       all_search = all_search) %>%
  mutate(
         microb_res = map_dbl(microbiome_search, ~entrez_search(db="pubmed", term=.x)$count),
         genom_res = map_dbl(genomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         proteo_res = map_dbl(proteomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         metabol_res = map_dbl(metabolomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         lipid_res = map_dbl(lipidomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         pheno_res = map_dbl(phenomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         transcr_res = map_dbl(transcriptomics_search, ~entrez_search(db="pubmed", term=.x)$count),
         ml_res = map_dbl(ml_search, ~entrez_search(db="pubmed", term=.x)$count),
         bioinfo_res = map_dbl(bioinfo_search, ~entrez_search(db="pubmed", term=.x)$count),
         pharma_res = map_dbl(pharma_search, ~entrez_search(db="pubmed", term=.x)$count),
         all_res = map_dbl(all_search, ~entrez_search(db="pubmed", term=.x)$count)
         ) 

paste("The search took", toc())
```

## Saving results in multiple formats
- CSV
- XLSX
- RDS

```{r}
write_csv(search_counts, "data/search_counts.csv", col_names = TRUE)
write.xlsx(search_counts, "data/search_counts.xlsx", col_names = TRUE)
saveRDS(search_counts, "data/search_counts.rds", col_names = TRUE)
```
